### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('\033[1)?

### ISSUE THREAD

**Issue by n4vn337** [maK-/parameth#15]
$ python3 ./parameth.py
File "./parameth.py", line 27
    print '\033[1;34m                                       |   |'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('\033[1)?

**Comment by shahrizz** [comment]
Yea...

Same thing, with both versions of python, I even installed all the requirements and it still did not work :/

**Comment by maK-** [comment]
Hey folks, 
This script is 4 years old and isn't written in python3. 
I do intend on eventually releasing an updated version but for now you'll just have to fork it and edit it yourself.
