### ISSUE TITLE
ImportError: No module named numpy

### ISSUE THREAD

**Issue by zaidnz** [maK-/parameth#16]
After i install the requirement file (without '-u' flag, it's said no such option) then when i try run the file "./parameth.py" it give me the below error.
Numpy installed already from the requirement.txt :

```
Traceback (most recent call last):
  File "./parameth.py", line 9, in <module>
    from numpy import array_split
ImportError: No module named numpy
```

**Comment by maK-** [comment]
You need to install the numpy python package :)

**Comment by zaidnz** [comment]
Yup i already installed, it i just installed requirement.txt using pip3 and it's worked fine .. thank you. :)
