### ISSUE TITLE
doesn'work and shows problems related to print command with no parantheses

### ISSUE THREAD

**Issue by c4ir0** [maK-/parameth#19]
doesn'work and shows problems related to print command with no parantheses

**Comment by c4ir0** [comment]
File "/home/kali/Desktop/parameth/parameth.py", line 27
    print '\033[1;34m                                       |   |'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by maK-** [comment]
Hey Cairo, this script runs in python2.x, you seem to be trying to run it with python3 ;)

**Comment by maK-** [comment]
closing out

**Comment by c4ir0** [comment]
actually I tried in with python, python2.7, python 3.7 still the same

**Comment by maK-** [comment]
No, you didn't.
