### ISSUE TITLE
Connection Error on parameter "offset"

### ISSUE THREAD

**Issue by arbazkiraak** [maK-/parameth#3]
python parameth.py -u http://makthepla.net/parameth/simpletest.php
                                       |   |
  __ \   _` |  __| _` | __ `__ \   _ \ **| __ \
  |   | (   | |   (   | |   |   |  __/ |   | | |
  .**/ __,_|_|  __,_|_|  _|  _|___|__|_| |_|
  _|
parameth v1.0 - find parameters and craic rocks
# Author: Ciaran McNally - https://makthepla.net

Establishing base figures...
POST data: 
Offset value: 0
GET: content-length-> 24  status-> 200
POST: content-length-> 24  status-> 200
Scanning it like you own it...
Connection Error on parameter "offset"

Kali 2.0 2016 x64 ,

**Comment by arbazhussain149** [comment]
i Guess this is Feature ,

python parameth.py -off 1 -u http://makthepla.net/parameth/simpletest.php

But Really Confused with its usage and  what should i define there , 

-----------------------------------------------

python parameth.py -off 1 -u http://makthepla.net/parameth/simpletest.php
                                       |   |
  __ \   _` |  __| _` | __ `__ \   _ \ __| __ \
  |   | (   | |   (   | |   |   |  __/ |   | | |
  .__/ \__,_|_|  \__,_|_|  _|  _|\___|\__|_| |_|
  _|
parameth v1.337 - find parameters and craic rocks
Author: Ciaran McNally - https://makthepla.net
================================================
Establishing base figures...
POST data: 
Offset value: 1
GET: content-length-> 24  status-> 200
POST: content-length-> 24  status-> 200
Scanning it like you own it...
Request Timed out on parameter "aa"

**Comment by arbazkiraak** [comment]
if i set -off, i got Request Timeout 

root@arbaz:~/Desktop/Pentest-Suite/Fuzz/parameth# python parameth.py -off 1 -u http://makthepla.net/parameth/simpletest.php
                                       |   |
  __ \   _` |  __| _` | __ `__ \   _ \ **| __ \
  |   | (   | |   (   | |   |   |  __/ |   | | |
  .**/ __,_|_|  __,_|_|  _|  _|___|__|_| |_|
  _|
parameth v1.337 - find parameters and craic rocks

# Author: Ciaran McNally - https://makthepla.net

Establishing base figures...
POST data: 
Offset value: 1
GET: content-length-> 24  status-> 200
POST: content-length-> 24  status-> 200
Scanning it like you own it...
Request Timed out on parameter "aa"

**Comment by arbazkiraak** [comment]
How to turn off the offset and perform normal scan ,

As shown in : 

https://camo.githubusercontent.com/fb1845f7a9025482e052639a0984b02305864e76/687474703a2f2f6d616b746865706c612e6e65742f706172616d6574682f706172616d6574682e706e67

Screenshot!
