### ISSUE TITLE
Adding two Headers to Requests

### ISSUE THREAD

**Issue by hussam-dh** [maK-/parameth#4]
Hello,
First of all, Thanks for the amazing tool, 
Secondly, I wonder if there is a possibility to add two headers to http requests,
I tried adding -H twice but only the last one is taken.
Thirdly, how does parameth handle the content types of requests, should I add them myself or it can detect them because this is the reason I am asking about adding two headers.

Looking forward to hearing from you.
Thanks again
Hussam

**Comment by hussam-dh** [comment]
it seems that using ":" in cookies causes parameth to fail.
thanks

**Comment by maK-** [comment]
Thanks hussam, I noticed the cookie problem myself alright recently

I'll take a look at this next week and see if I can come up with an easy fix ;)

**Comment by maK-** [comment]
As for content-types, I don't detect differences in them but possibly is something I can add 
fixing the header problem should hopefully resolve this too

**Comment by hussam-dh** [comment]
Thanks @maK-

**Comment by sjortiz** [comment]
@maK- Do you need any help in this one?

**Comment by maK-** [comment]
Pushed a solution there, forgot about this request tbh
Example: ./parameth.py -u http://127.0.0.1:9999/blah -H example:1 header:2 test:3

nc -lvp 9999
listening on [any] 9999 ...
connect to [127.0.0.1] from localhost [127.0.0.1] 55220
GET /blah HTTP/1.1
Host: 127.0.0.1:9999
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-agent: parameth v1.0
test: 3
header: 2
example: 1
