### ISSUE TITLE
JWT Custom Header Error

### ISSUE THREAD

**Issue by Hax0rG1rl** [maK-/parameth#7]
Hi, 

Thank for your hard work building this one!

Got an issue with trying to make it work inserting JWT header which looks like this: 

Authorisation: Bearer almostendlessblaalmostendlessblaalmostendlessblaalmostendlessblaalmostendlessbla..

Used CLI: 

```
./parameth.py -u https://target -H "Authorization: Bearer eyJ0eXAiOJhbGciOiJSUzI1NiIsImp0aSI6IjI5ZmZk....zBhM2VhMzY5MjI3NDhiZDk3ZjY0NDJkYWFiNTA0ZDA5Y2E0MWQwMzI0MGIxMDFiYjVmMTBiNmI3ZDYzYTM5In0.eyJhdWQiOiIyIiwianRpIjoiMjlmZmQyNjY5OGVkZGNiNmNjMGEzZWEzN...." --cookie "crumb=[...]; ss_cvr=[...]; __hstc=[...];" --proxy http://127.0.0.1:8084
```
Any ideas? :)

Thanks!

**Comment by sjortiz** [comment]
@Hax0rG1rl is this still happening for you? What is the error it displays?
@maK-  mind if I help out in here?

**Comment by maK-** [comment]
feel free! I'll check pull requests if any too
