### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by samuel823** [maK-/parameth#8]
i getting request timed out on parameter , when i run the tools , do u have any idea how to fix it?

**Comment by maK-** [comment]
Sounds to me like the tool is working,
what parameter is the test timing out on?

If every parameter is timing out are you doing any of the following:
+ Making sure you are not using too many threads against a poor web application
+ Making sure you don't have proxy enabled on burp (if forwarding to burp)
+ Making sure your proxy is actually working
+ Some parameters can cause a DOS on an application level, this can also cause timeouts
+ Sometimes the data returned on the page is large and it takes a long time to load

You can set a manual timeout between requests using -t

You can also modify the code to increase the timeout time for the actual request if it's too many requests causing you problems

The other problem could be that the page takes longer than 10 seconds to load and you need to for example, update all the instances where requests is set with "timeout=10"
https://github.com/maK-/parameth/blob/master/parameth.py#L254

**Comment by samuel823** [comment]
im fine now , i just restart kali and no more time out ty bro
